/* Generated By:JavaCC: Do not edit this line. LugosiConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LugosiConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int ACHAVES = 6;
  /** RegularExpression Id. */
  int FCHAVES = 7;
  /** RegularExpression Id. */
  int VOID = 8;
  /** RegularExpression Id. */
  int LET = 9;
  /** RegularExpression Id. */
  int SEMICOLON = 10;
  /** RegularExpression Id. */
  int TYPE_FLOAT = 11;
  /** RegularExpression Id. */
  int TYPE_BOOL = 12;
  /** RegularExpression Id. */
  int ASSINGMENT = 13;
  /** RegularExpression Id. */
  int OPEN_PARENTHESIS = 14;
  /** RegularExpression Id. */
  int CLOSE_PARENTHESIS = 15;
  /** RegularExpression Id. */
  int IF = 16;
  /** RegularExpression Id. */
  int WHILE = 17;
  /** RegularExpression Id. */
  int DO = 18;
  /** RegularExpression Id. */
  int READIO = 19;
  /** RegularExpression Id. */
  int RETURN = 20;
  /** RegularExpression Id. */
  int PRINTIO = 21;
  /** RegularExpression Id. */
  int TRUE = 22;
  /** RegularExpression Id. */
  int FALSE = 23;
  /** RegularExpression Id. */
  int OP_PLUS = 24;
  /** RegularExpression Id. */
  int OP_MINUS = 25;
  /** RegularExpression Id. */
  int OP_MULTIPLICATION = 26;
  /** RegularExpression Id. */
  int OP_DIVISION = 27;
  /** RegularExpression Id. */
  int OP_LOGIC_AND = 28;
  /** RegularExpression Id. */
  int OP_LOGIC_OR = 29;
  /** RegularExpression Id. */
  int COMPARISON_LESS_THAN = 30;
  /** RegularExpression Id. */
  int COMPARISON_GREATER_THAN = 31;
  /** RegularExpression Id. */
  int COMPARISON_EQUALS = 32;
  /** RegularExpression Id. */
  int COMMA = 33;
  /** RegularExpression Id. */
  int DEF = 34;
  /** RegularExpression Id. */
  int NUM = 35;
  /** RegularExpression Id. */
  int ID = 36;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"{\"",
    "\"}\"",
    "\"void\"",
    "\"let\"",
    "\";\"",
    "\"float\"",
    "\"bool\"",
    "\":=\"",
    "\"(\"",
    "\")\"",
    "\"if\"",
    "\"while\"",
    "\"do\"",
    "\"readIO\"",
    "\"return\"",
    "\"printIO\"",
    "\"true\"",
    "\"false\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&&\"",
    "\"||\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "\",\"",
    "\"def\"",
    "<NUM>",
    "<ID>",
  };

}
